# Thong tin ket noi DB
spring.datasource.url=jdbc:postgresql://localhost:5432/dbcnpm
spring.datasource.username=postgres
spring.datasource.password=13579
spring.datasource.driver-class-name=org.postgresql.Driver

# Chi dinh ro Dialect cho Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Tu dong cap nhat bang va hien SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true