# Th�ng tin k?t n?i DB
spring.datasource.url=jdbc:postgresql://localhost:5432/dbcnpm
spring.datasource.username=postgres
spring.datasource.password=13579
spring.datasource.driver-class-name=org.postgresql.Driver

# Ch? ??nh r� Dialect cho Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# T? ??ng c?p nh?t b?ng v� hi?n SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true